version: "3"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: >
      npm run dev -- --host 0.0.0.0 --port 3000

volumes:
  node_modules:
