[tool.black]
line-length = 99
exclude = '''
  \.git
  | \.github
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | manage.py
  | migrations
  | scripts
  | venv
'''

[tool.isort]
profile = "black"
line_length = 99
known_pytest = "pytest,factory,faker"
known_django = "django"
known_drf = "rest_framework"
sections = "FUTURE,STDLIB,PYTEST,DJANGO,DRF,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
skip = '''
    .git
    .github
    .mypy_cache
    .pytest_cache
    .tox
    .venv
    manage.py
    settings.py
    migrations
    scripts
'''
no_lines_before = "LOCALFOLDER"